### ISSUE TITLE
アプリを開いている時にオンライン状態にする

### ISSUE THREAD

**Issue by take-iwa** [MaruiorimonoTeam/couple-t-ios#126]
アンドロイドの方で話しましたが、
デザインツール使用中だけでなく、アプリを起動している間はオンライン状態とするようにしてください。

**Comment by alexeypolitov** [comment]
@take-iwa こちらの作業は大変ですので、別料金かかりますがよろしいですか？

**Comment by take-iwa** [comment]
@alexeypolitov ひとまず、今のままということになりました。
念のため、ラベルをstockにしておきます。
